In [2]:
import pandas as pd
import numpy as np
from konlpy.tag import Okt
from sklearn.feature_extraction.text import CountVectorizer

# 데이터 불러오기

In [3]:
df=pd.read_csv('GS건설_ward1_cluster1.csv')
df

Unnamed: 0                                             review  target  \
0             31  공기청정기 이런적있나요 공기청정기가 특정 시간 아침 시 전후 갑자기 에서 까지 치솟...       1   
1            353  자취방에 공기청정기 모셨는데 그냥 시험삼아 궁금해서 방구껴봤는데 바로 울그락불그락 ...       1   
2            358  공기청정기는 몇시간 사용하세요 공기청정기 구입하려고합니다 공기청정기는 하루종일 작동...       1   
3            415  나 공기청정기 시간 켜놓는데 집밖에 나갈때도 켜놓음 먼지 빨아댕기라고 왜 회사같은데...       1   
4            433                      일정도 집비우게됫는데정수기랑 공기청정기 켜놓고갈까말까       1   
...          ...                                                ...     ...   
2826      112188  전기 유틸리티 관련해서 여쭤봐요 저희 집은 타운하우스로 라는 지역전기를 쓰고 있어요...       1   
2827      114635  빌트인가스렌즈 점화되고 불붙은데 금방 꺼지는건 왜일까요 빌트인 구 가스렌지 사용하는...       1   
2828      117323  형들 옥탑 별로야 나 테라스 쓰고 싶어서 옥탑가고 싶은데 단점 뭐있음 여름에 덥고 ...       1   
2829      118288  빌트인캠 주차중 상시 키면 안되나용 하이브리드인데 빌트인캠 주차중 상시켜놓으면 설정...       1   
2830      118434  형들 냉장고 문짝 이거 어떡하면 좋을까 빌트인 돼있는 냉장고 문짝을 고정하는게 부서...       1   

      cluster  
0           1  
1           1  
2           1  
3           1  
4           1  
...       ...  
2826        1  
2827        1  
2828        1  
2829        1  
2830        1  

[2831 rows x 4 columns]

In [4]:
okt = Okt() 
def preprocess_okt(text):
    #text = spacing(text) #띄어쓰기 보정 위에서 했으면 필요없습니다
    pos_words = okt.pos(text, stem=True)
    words = [word for word, tag in pos_words if tag in ['Noun', 'Adjective', 'Verb'] ]
    stopwords = ['의','가','이','은','들','는','좀','잘','걍','과','아니다',
                 '이렇다','저렇다','도','다','돼다','최고','되다','를','같다',
                 '되었다','오다','가다','으로','자','에','와','한','하다','것',
                 '수','있다','않다','그','이다','이었다', '안','억','이건','정도',
                 '개']
    stopped_words = [w for w in words if not w in stopwords]
    return ', '.join(stopped_words)

In [5]:
df['review_token']=df['review'].apply(preprocess_okt)
df['review_token']= [ _ for _ in df.review_token]

#빈 값 확인
# empty_index = [index for index, sentence in zip(df.index,df['review_token']) if len(sentence) < 1]
# print(empty_index) 
df

Unnamed: 0                                             review  target  \
0             31  공기청정기 이런적있나요 공기청정기가 특정 시간 아침 시 전후 갑자기 에서 까지 치솟...       1   
1            353  자취방에 공기청정기 모셨는데 그냥 시험삼아 궁금해서 방구껴봤는데 바로 울그락불그락 ...       1   
2            358  공기청정기는 몇시간 사용하세요 공기청정기 구입하려고합니다 공기청정기는 하루종일 작동...       1   
3            415  나 공기청정기 시간 켜놓는데 집밖에 나갈때도 켜놓음 먼지 빨아댕기라고 왜 회사같은데...       1   
4            433                      일정도 집비우게됫는데정수기랑 공기청정기 켜놓고갈까말까       1   
...          ...                                                ...     ...   
2826      112188  전기 유틸리티 관련해서 여쭤봐요 저희 집은 타운하우스로 라는 지역전기를 쓰고 있어요...       1   
2827      114635  빌트인가스렌즈 점화되고 불붙은데 금방 꺼지는건 왜일까요 빌트인 구 가스렌지 사용하는...       1   
2828      117323  형들 옥탑 별로야 나 테라스 쓰고 싶어서 옥탑가고 싶은데 단점 뭐있음 여름에 덥고 ...       1   
2829      118288  빌트인캠 주차중 상시 키면 안되나용 하이브리드인데 빌트인캠 주차중 상시켜놓으면 설정...       1   
2830      118434  형들 냉장고 문짝 이거 어떡하면 좋을까 빌트인 돼있는 냉장고 문짝을 고정하는게 부서...       1   

      cluster                                       review_token  
0           1  공기청정기, 적다, 공기청정기, 특정, 시간, 아침, 시, 전후, 갑자기, 치솟다,...  
1           1  자취, 방, 공기청정기, 모시다, 그냥, 시험, 삼다, 궁금하다, 방구, 끼다, 보...  
2           1  공기청정기, 시간, 사용, 공기청정기, 구입, 공기청정기, 하루, 종일, 작동시키다...  
3           1  나, 공기청정기, 시간, 켜다, 집, 나가다, 때, 켜다, 먼지, 빨, 댕기, 왜,...  
4           1                  일정, 집, 비우다, 됫, 늘다, 정수기, 공기청정기, 켜다  
...       ...                                                ...  
2826        1  전기, 유틸리티, 관련, 여쭈다, 보다, 저희, 집다, 타운하우스, 지역, 전기, ...  
2827        1  빌트, 가스, 렌즈, 점화, 불, 붙다, 금방, 꺼지다, 왜, 요, 빌트, 구, 가...  
2828        1  형, 옥탑, 별로, 나, 테라스, 쓰다, 싶다, 옥, 타다, 싶다, 단점, 뭐, 여...  
2829        1  빌트, 캠, 주차, 상시, 키, 안되다, 하이브리드, 빌트, 캠, 주차, 상, 시키...  
2830        1  형, 냉장고, 문짝, 거, 어떡하다, 좋다, 빌트, 냉장고, 문짝, 고정, 부서지다...  

[2831 rows x 5 columns]

# 토큰화된 단어를 리스트로 만들기

In [6]:
total_token=df['review_token'].tolist()
total_token

['공기청정기, 적다, 공기청정기, 특정, 시간, 아침, 시, 전후, 갑자기, 치솟다, 작동, 왜, 걸, 끄다, 거실, 놓다, 쓰다, 근처, 환풍기, 없다, 형, 일어나서, 방구, 끼다, 그렇다, 나다, 그렇다, 알, 남편, 놀렷는데, 남편, 안방, 자고, 잇다, 난, 드레스, 룸, 잇다, 사이, 거실, 아무, 없다, 울리다, 입냄새, 혹시, 응, 타임, 시간대, 가습기, 켜, 가습기, 침실, 침실, 가습기, 켜다, 아침, 방문, 열다, 거실, 청기, 미세먼지, 확, 올라가다, 센서, 청소, 미흡하다, 측정, 오류, 쓸다, 이불, 먼지, 씌우다, 거실, 나오다, 아무, 돌아다니다, 시간, 임',
 '자취, 방, 공기청정기, 모시다, 그냥, 시험, 삼다, 궁금하다, 방구, 끼다, 보다, 바로, 락불그락, 화, 내면, 모터, 돌리다, 거, 들다, 한번, 해보다, 난, 사람, 이면, 초적, 궁금하다, 거, 생각, 필터, 비닐, 뜯다, 나다, 해봣는데, 은근, 쾌감, 죽여주다, 웃기, 너, 방금, 샤워, 청기, 앞, 지나가다, 빨갛다, 불, 들어오다, 공기, 청정, 최대, 모드, 돌아가다, 때, 뭐, 생각, 들다, 씻다, 니, 싫다, 작다, 물방울, 입자, 인식, 거, 요, 분무기, 물, 뿌리, 미치다, 돌아가다, 가스, 방구뀌, 빨간색, 바뀌다, 자다, 작동, 사다',
 '공기청정기, 시간, 사용, 공기청정기, 구입, 공기청정기, 하루, 종일, 작동시키다, 가요, 하루, 시간, 보통, 사용, 죙일, 일, 쭈욱이, 일요, 청소, 때, 끄다, 계속, 켜, 두다, 사람, 생활, 모든, 시간, 요, 시간, 풀, 일, 전, 자다, 때, 끄다, 가습기, 틀다, 야하다, 환기, 요리, 때, 빼다, 종일, 계속, 자다, 때, 빼다, 계속, 틀다, 두다, 저, 거실, 위, 닉스, 대형, 놓다, 방, 가성, 비, 공기청정기, 놓다, 가성, 비, 공기청정기, 매일, 돌리다, 가성, 비, 공기청정기, 위, 닉스, 더, 좋다, 혹시, 어떳모델, 정보, 궁금하다, 쪽지, 드리다, 거의, 알

# 동시출현매트릭스 만들기

In [7]:
# 동시출현빈도 매트릭스
cv=CountVectorizer()

X = cv.fit_transform(total_token)
Xc = (X.T * X)
Xc.setdiag(0) #대각선 원소를 0으로
Xc=Xc.todense() # 밀집행렬로 변형 (matrix형으로)
Xc

matrix([[0, 0, 1, ..., 0, 0, 0],
        [0, 0, 3, ..., 0, 0, 0],
        [1, 3, 0, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [8]:
names = cv.get_feature_names()

#Xc.toarray() .todense와 같지만 array형태로 만들어줘서 dataframe에 넣음
matrix = pd.DataFrame(data =Xc, columns = names, index = names)
matrix.index

/Users/heojiyeon/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


Index(['가가', '가게', '가격', '가계', '가계부', '가구', '가구라', '가군', '가기', '가까워지다',
       ...
       '힐링', '힘내다', '힘드넴', '힘드다', '힘들다', '힘빠지다', '힘쓰다', '힘없다', '힘주다', '힙쳐'],
      dtype='object', length=10793)

In [9]:
matrix

가가  가게  가격  가계  가계부  가구  가구라  가군  가기  가까워지다  ...  힐링  힘내다  힘드넴  힘드다  \
가가     0   0   1   0    0   0    0   0   0      0  ...   0    0    0    0   
가게     0   0   3   0    3   0    0   0   0      1  ...   0    0    0    2   
가격     1   3   0   0    1  31    0   0   0      0  ...   0    1    0   11   
가계     0   0   0   0    3   0    0   0   0      0  ...   0    0    0    0   
가계부    0   3   1   3    0  15    0   0   0      0  ...   0    0    0   10   
...   ..  ..  ..  ..  ...  ..  ...  ..  ..    ...  ...  ..  ...  ...  ...   
힘빠지다   0   0   0   0    0   0    0   0   0      0  ...   0    0    0    1   
힘쓰다    0   0   0   0    0   0    0   0   0      0  ...   0    0    0    0   
힘없다    0   0   0   0    0   0    0   0   0      0  ...   0    0    0    1   
힘주다    0   0   1   0    0   0    0   0   0      0  ...   0    0    0    0   
힙쳐     0   0   0   0    0   0    0   0   0      0  ...   0    0    0    0   

      힘들다  힘빠지다  힘쓰다  힘없다  힘주다  힙쳐  
가가      0     0    0    0    0   0  
가게     12     0    0    0    0   0  
가격     23     0    0    0    1   0  
가계      0     0    0    0    0   0  
가계부    11     0    0    0    0   0  
...   ...   ...  ...  ...  ...  ..  
힘빠지다    0     0    0    0    0   0  
힘쓰다     0     0    0    0    0   0  
힘없다     1     0    0    0    0   0  
힘주다     0     0    0    0    0   0  
힙쳐      0     0    0    0    0   0  

[10793 rows x 10793 columns]

In [10]:
matrix.to_csv('co_occurrence matrix_cluster1.csv', encoding = 'utf-8-sig', sep = ',')

# 만약 평균 기준으로 cutoff 한다면!
- 노드 빈도가 평균 이상일 경우만 살려주고 싶다면 사용하세요
- 데이터를 가볍게 만들길 원한다면,,

In [11]:
mean_val = np.mean(Xc[Xc!=0]) # Xc의 평균값 계산
Xc[Xc < int(mean_val)] = 0 # 평균 이하인 값을 0으로 바꾸기

In [12]:
# Xc를 numpy array로 변환
Xc = np.array(Xc)

# 각 행과 열의 합 구하기
row_sum = np.sum(Xc, axis=1)
col_sum = np.sum(Xc, axis=0)

# 합이 0인 인덱스 찾기
zero_row_idx = np.where(row_sum == 0)[0]
zero_col_idx = np.where(col_sum == 0)[0]

# 해당 인덱스 삭제
Xc = np.delete(Xc, zero_row_idx, axis=0)
Xc = np.delete(Xc, zero_col_idx, axis=1)

# 결과 출력
print(Xc)
Xc.shape

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(8330, 8330)

In [13]:
names = cv.get_feature_names()
Name = [val for i, val in enumerate(names) if i not in zero_row_idx]
matrix = pd.DataFrame(data =Xc, columns = Name, index = Name)
matrix.index

/Users/heojiyeon/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


Index(['가가', '가게', '가격', '가계', '가계부', '가구', '가군', '가기', '가까워지다', '가까이',
       ...
       '히힛', '힐듯', '힐링', '힘내다', '힘드다', '힘들다', '힘빠지다', '힘쓰다', '힘없다', '힙쳐'],
      dtype='object', length=8330)

In [15]:
matrix.

가가  가게  가격  가계  가계부  가구  가군  가기  가까워지다  가까이  ...  히힛  힐듯  힐링  힘내다  힘드다  \
가가     0   0   0   0    0   0   0   0      0    0  ...   0   0   0    0    0   
가게     0   0   0   0    0   0   0   0      0    0  ...   0   0   0    0    0   
가격     0   0   0   0    0  31   0   0      0   12  ...   0   0   0    0   11   
가계     0   0   0   0    0   0   0   0      0    0  ...   0   0   0    0    0   
가계부    0   0   0   0    0  15   0   0      0    0  ...   0   0   0    0   10   
...   ..  ..  ..  ..  ...  ..  ..  ..    ...  ...  ...  ..  ..  ..  ...  ...   
힘들다    0  12  23   0   11  11   0   0      0    9  ...   0   0   0    0    9   
힘빠지다   0   0   0   0    0   0   0   0      0    0  ...   0   0   0    0    0   
힘쓰다    0   0   0   0    0   0   0   0      0    0  ...   0   0   0    0    0   
힘없다    0   0   0   0    0   0   0   0      0    0  ...   0   0   0    0    0   
힙쳐     0   0   0   0    0   0   0   0      0    0  ...   0   0   0    0    0   

      힘들다  힘빠지다  힘쓰다  힘없다  힙쳐  
가가      0     0    0    0   0  
가게     12     0    0    0   0  
가격     23     0    0    0   0  
가계      0     0    0    0   0  
가계부    11     0    0    0   0  
...   ...   ...  ...  ...  ..  
힘들다     0     0    0    0   0  
힘빠지다    0     0    0    0   0  
힘쓰다     0     0    0    0   0  
힘없다     0     0    0    0   0  
힙쳐      0     0    0    0   0  

[8330 rows x 8330 columns]

In [16]:
matrix.to_csv('co_occurrence matrix_cluster1.csv', encoding = 'utf-8-sig', sep = ',')